### ISSUE TITLE
Bot seems not able to adjust to 7.28 change

### ISSUE THREAD

**Issue by JingyaYing** [adamqqqplay/dota2ai#36]
Many bots are not learning ult e.g. NEC && PA && sniper due to potential shard skill index change.
We should be able to adjust the skill index to fix it.

Btw, I am a developer, and dota2 bot fans really interested in contributing. Please let me know if the code here is the latest and might need some help ramp up

**Comment by adamqqqplay** [comment]
Hello, Thank you very much for the bug you pointed out. Because the previous developers did not have enough time to maintain, there are many places that are no longer compatible with Dota2.

We welcome everyone to contribute to this project. If you are interested, you can refer to the information in README.md to understand the structure of the project. 

The code in github is the latest, as you can see from the commit log, the last version supported by AI is 7.23. If you want to make AI compatible with 7.28, you may need to read the update logs of these versions of Dota 2 and apply the game changes in each version to this AI. Fortunately, most of the balance changes will not affect the AI's work, only gameplay changes will prevent the AI from working properly.

Hope the above content can help you, if you have other questions, welcome further discussion.
